/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import NN.API.Common
public import NN.API.Macros
public import NN.API.TList
public import NN.MLTheory.CROWN.Core
public import NN.MLTheory.CROWN.Graph
public import NN.Runtime.PyTorch.Import.Core
public import NN.Verification.TorchLean.Compile
public import NN.Verification.Util.Json
import Lean.Data.Json

/-!
# Digits certified robustness

Certified accuracy for a linear classifier on sklearn's digits dataset.

Workflow:
- Train a small linear classifier on sklearn's digits (8x8) in Python and export:
  - weights JSON (`digits_linear_weights.json`)
  - test dataset JSON (`digits_test.json`)
- In Lean, load the weights + dataset and compute certified accuracy under an `ℓ∞` input box using:
  - IBP (`runIBP`)
  - a simple CROWN/affine pass (`runAffine` + `AffineVec.eval_on_box`)

Run:
  `lake exe verify -- digits`
  `lake exe verify -- digits --eps=0.02 --max=360`
  `lake exe verify -- digits --float32-mode ieee754exec --eps=0.02`

Regenerate assets:
  `python3 scripts/verification/robustness/train_digits_linear.py`
-/

@[expose] public section


namespace NN.Verification.Robustness.Digits

open _root_.Spec
open _root_.Spec.Tensor
open NN.API

open NN.MLTheory.CROWN.Graph
open NN.MLTheory.CROWN
open Import
open Lean
open Json
open NN.Verification.Json

/-- Flattened input dimension for sklearn digits (8×8). -/
def inDim : Nat := 64
/-- Number of classes (digits 0..9). -/
def outDim : Nat := 10

/-- Weight shape for a linear classifier `y = Wx + b` (10×64). -/
def WShape : Shape := .dim outDim (.dim inDim .scalar)
/-- Bias shape for a linear classifier (10). -/
def bShape : Shape := .dim outDim .scalar
/-- Input shape (64). -/
def xShape : Shape := .dim inDim .scalar
/-- Output/logit shape (10). -/
def yShape : Shape := .dim outDim .scalar

/-- Parameter shapes list used by the compiled TorchLean program (`[W, b]`). -/
def paramShapes : List Shape := [WShape, bShape]

/-- CLI options for the digits certified-accuracy workflow. -/
structure DigitsOpts where
  /-- Weights JSON path (PyTorch export). -/
  weights : String := "NN/Examples/Verification/Robustness/digits_linear_weights.json"
  /-- Dataset JSON path (PyTorch export). -/
  dataset : String := "NN/Examples/Verification/Robustness/digits_test.json"
  /-- L∞ perturbation radius around each input example. -/
  eps     : Float  := 0.02
  /-- Max number of examples to evaluate (for local checks). -/
  max     : Nat    := 100
  deriving Repr

/-- Usage string printed on `--help` / `-h`. -/
def usage : String :=
  String.intercalate "\n" [
    "Usage:",
    ("  lake exe verify -- digits [--weights=PATH.json] " ++
      "[--dataset=PATH.json] [--eps=0.02] [--max=100]"),
    "",
    "Notes:",
    "  - DType flags are also accepted (e.g. --float32-mode ieee754exec).",
    ("  - Assets are generated by: python3 " ++
      "scripts/verification/robustness/train_digits_linear.py")
  ]

/-- Parse a float literal written as JSON (e.g. `0.02`). -/
def parseFloatLit (s : String) : Option Float :=
  match Json.parse s with
  | .ok (.num n) => some n.toFloat
  | _ => none

/-- Parse CLI args into `DigitsOpts` (returns `usage` as the error message on `--help`). -/
def parseArgs : List String → Except String DigitsOpts
  | [] => .ok {}
  | a :: rest =>
    match parseArgs rest with
    | .error e => .error e
    | .ok o =>
      if a == "--" then
        .ok o
      else if a == "--help" || a == "-h" then
        .error usage
      else if a.startsWith "--weights=" then
        .ok { o with weights := (a.drop 10).toString }
      else if a.startsWith "--dataset=" then
        .ok { o with dataset := (a.drop 10).toString }
      else if a.startsWith "--eps=" then
        match parseFloatLit (a.drop 6).toString with
        | some v => .ok { o with eps := v }
        | none => .error s!"bad --eps: {a}"
      else if a.startsWith "--max=" then
        match (a.drop 6).toString.toNat? with
        | some v => .ok { o with max := v }
        | none => .error s!"bad --max: {a}"
      else
        .error s!"unknown arg: {a}\n\n{usage}"

/-- TorchLean program for the linear classifier `y = Wx + b`. -/
def classifier {α : Type} [Context α] [DecidableEq Shape] :
    TorchLean.Program α (paramShapes ++ [xShape]) yShape :=
  fun {m} _ _ =>
    fun w b x =>
      (TorchLean.linear (m := m) (α := α) (inDim := inDim) (outDim := outDim) w b x
        : m (TorchLean.RefTy (m := m) (α := α) yShape))

/-- Clamp a tensor elementwise into `[0,1]` (used for input normalization). -/
def clamp01 {α : Type} [Context α] {s : Shape} (t : Tensor α s) : Tensor α s :=
  Spec.mapTensor (fun x => max (0 : α) (min (1 : α) x)) t

/-- Argmax for a `Float` vector tensor (returns `0` if `n = 0`). -/
def argmaxFloat {n : Nat} (t : Tensor Float (.dim n .scalar)) : Nat :=
  if h : n = 0 then
    0
  else
    let i0 : Fin n := ⟨0, Nat.pos_of_ne_zero h⟩
    let init : (Fin n × Float) := (i0, Tensor.vecGet t i0)
    let (best, _) :=
      (List.finRange n).foldl (fun (acc : Fin n × Float) i =>
        let (bestI, bestV) := acc
        let vi := Tensor.vecGet t i
        if vi > bestV then (i, vi) else (bestI, bestV)) init
    best.val

/--
Certify top-1 correctness from output bounds.

Given elementwise bounds `lo <= y <= hi`, this returns `true` if the lower bound on the true-label
logit exceeds the upper bounds of all other logits.
-/
def certifiedTop1 {α : Type} [Context α]
    (lo hi : Tensor α yShape) (label : Nat) : Bool :=
  if h : label < outDim then
    let y : Fin outDim := ⟨label, h⟩
    let loY := Tensor.vecGet lo y
    let maxOther? :=
      (List.finRange outDim).foldl (fun (acc : Option α) i =>
        if i = y then acc
        else
          match acc with
          | none => some (Tensor.vecGet hi i)
          | some m => some (max m (Tensor.vecGet hi i))) none
    match maxOther? with
    | none => true
    | some m => Context.gtBool loY m
  else
    false

/-- Load linear classifier weights exported from PyTorch into a typed `LinearSpec`. -/
def loadWeights (path : String) : IO (Spec.LinearSpec Float inDim outDim) := do
  let j ← readJsonObjectFile path
  match j with
  | .obj o =>
      let wJ ←
        match o.get? "layers.0.weight" with
        | some jw => pure jw
        | none => throw <| IO.userError "Missing weights key: layers.0.weight"
      let bJ ←
        match o.get? "layers.0.bias" with
        | some jb => pure jb
        | none => throw <| IO.userError "Missing weights key: layers.0.bias"
      let some wFn := Import.PyTorch.parseFloatMatrix outDim inDim wJ
        | throw <| IO.userError "layers.0.weight must be a float matrix of shape [10][64]"
      let some bFn := Import.PyTorch.parseFloatVec outDim bJ
        | throw <| IO.userError "layers.0.bias must be a float array of length 10"
      let w : Tensor Float WShape := Spec.matrixTensor wFn
      let b : Tensor Float bShape := Spec.vectorTensor bFn
      pure { weights := w, bias := b }
  | _ =>
      throw <| IO.userError "Weights JSON must be an object"

/-- Load the digits test dataset exported from Python (JSON). -/
def loadDataset (path : String) : IO (Array (Tensor Float xShape × Nat)) := do
  let j ← readJsonObjectFile path
  let examples ←
    match ← optionalField? j "examples" "dataset" with
    | none => pure #[]
    | some examplesJ => expectArray examplesJ "dataset.examples"
  let mut out : Array (Tensor Float xShape × Nat) := #[]
  for e in examples do
    let eo ← expectObj e "dataset example"
    let xJ ← expectField eo "x" "dataset example"
    let y ← expectFieldNat eo "y" "dataset example"
    let some vec := Import.PyTorch.parseFloatVec inDim xJ
      | throw <| IO.userError "Dataset example 'x' must be a float array of length 64"
    let xT : Tensor Float xShape := Spec.vectorTensor vec
    out := out.push (xT, y)
  pure out

/-- Running counters for the digits certified-accuracy workflow. -/
structure DigitsReport where
  /-- Number of examples checked. -/
  total : Nat := 0
  /-- Number of clean examples classified correctly by the exported model. -/
  nominalOk : Nat := 0
  /-- Number of examples certified by interval bound propagation. -/
  ibpOk : Nat := 0
  /-- Number of examples certified by the affine CROWN pass. -/
  crownOk : Nat := 0
  deriving Repr

/--
Run the certified-accuracy evaluation once, under a chosen scalar backend `α`.

This compiles the linear classifier to the verifier IR, then checks each example's `L∞` box using
IBP and a simple affine pass.
-/
def runOnce {α : Type} [Semantics.Scalar α] [DecidableEq Shape] [ToString α]
    [Runtime.Scalar α] (opts : DigitsOpts) : IO DigitsReport := do
  let cast : Float → α := Runtime.ofFloat
  let linF ← loadWeights opts.weights
  let examples0 ← loadDataset opts.dataset
  let examples := examples0.take opts.max

  let params : tlist.TList α paramShapes :=
    tlist!
      (NN.API.Common.castTensor cast linF.weights),
      (NN.API.Common.castTensor cast linF.bias)

  let compiled ←
    match NN.Verification.TorchLean.compileForward1
          (α := α) (paramShapes := paramShapes) (inShape := xShape) (outShape := yShape)
          (classifier (α := α)) params with
    | .ok c => pure c
    | .error e => throw <| IO.userError e

  IO.println s!"[digits] compiled IR nodes: {compiled.graph.nodes.size}"

  let eps : α := cast opts.eps
  let rad : Tensor α xShape := Spec.fill (α := α) eps xShape
  let ctx : AffineCtx := { inputId := compiled.inputId, inputDim := inDim }

  let mut report : DigitsReport := {}

  for (xF, yNat) in examples do
    report := { report with total := report.total + 1 }

    let yF : Tensor Float yShape := Spec.linearSpec (α := Float) linF xF
    if argmaxFloat (n := outDim) yF = yNat then
      report := { report with nominalOk := report.nominalOk + 1 }

    let x0 : Tensor α xShape := NN.API.Common.castTensor cast xF
    let loX := clamp01 (Tensor.subSpec x0 rad)
    let hiX := clamp01 (Tensor.addSpec x0 rad)
    let xB : FlatBox α :=
      { dim := inDim, lo := loX, hi := hiX }

    let ps : ParamStore α :=
      { compiled.ps with inputBoxes := compiled.ps.inputBoxes.insert compiled.inputId xB }

    let ibp := runIBP (α := α) compiled.graph ps
    let some outB := ibp[compiled.outputId]! | throw <| IO.userError "IBP produced no output box"
    if hOut : outB.dim = outDim then
      let loY : Tensor α yShape := by
        simpa [yShape] using Tensor.castVecDim (α := α) (n := outB.dim) (m := outDim) hOut outB.lo
      let hiY : Tensor α yShape := by
        simpa [yShape] using Tensor.castVecDim (α := α) (n := outB.dim) (m := outDim) hOut outB.hi
      if certifiedTop1 (α := α) loY hiY yNat then
        report := { report with ibpOk := report.ibpOk + 1 }
    else
      throw <| IO.userError s!"Unexpected output dim {outB.dim} (expected {outDim})"

    let affs := runAffine (α := α) compiled.graph ps ctx ibp
    match affs[compiled.outputId]! with
    | none =>
        -- Should not happen for linear/relu/linear graphs.
        pure ()
    | some outAff =>
        if hIn : outAff.inDim = inDim then
          if hOut : outAff.outDim = outDim then
            let xBox : Box α (.dim outAff.inDim .scalar) :=
              { lo := Tensor.castVecDim (α := α) (n := inDim) (m := outAff.inDim) hIn.symm xB.lo
                hi := Tensor.castVecDim (α := α) (n := inDim) (m := outAff.inDim) hIn.symm xB.hi }
            let outC := NN.MLTheory.CROWN.AffineVec.evalOnBox (α := α) outAff.aff xBox
            let loY : Tensor α yShape := by
              simpa [yShape] using Tensor.castVecDim (α := α) (n := outAff.outDim) (m := outDim)
                hOut outC.lo
            let hiY : Tensor α yShape := by
              simpa [yShape] using Tensor.castVecDim (α := α) (n := outAff.outDim) (m := outDim)
                hOut outC.hi
            if certifiedTop1 (α := α) loY hiY yNat then
              report := { report with crownOk := report.crownOk + 1 }
          else
            pure ()
        else
          pure ()

  IO.println s!"[digits] examples={report.total} eps={opts.eps}"
  IO.println s!"[digits] nominal accuracy: {report.nominalOk}/{report.total}"
  IO.println s!"[digits] certified (IBP):   {report.ibpOk}/{report.total}"
  IO.println s!"[digits] certified (CROWN): {report.crownOk}/{report.total}"
  pure report

/--
CLI entry point for the digits certified-robustness workflow.

This is wired into `lake exe verify -- digits`.
-/
def main (args : List String) : IO Unit := do
  IO.println "== TorchLean digits certified robustness =="
  let (dtype, rest) ←
    match NN.API.DType.parseAndStrip args with
    | .ok v => pure v
    | .error msg => throw <| IO.userError msg
  NN.API.DType.log dtype
  let opts ←
    match parseArgs rest with
    | .ok o => pure o
    | .error msg => throw <| IO.userError msg
  match (← NN.API.DType.withRuntime dtype (fun {α} _ _ _ _ => do
      let _ ← runOnce (α := α) opts
      pure ())) with
  | .ok () => pure ()
  | .error msg => throw <| IO.userError msg

end NN.Verification.Robustness.Digits
