/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import NN.API.Common
public import NN.API.Macros
public import NN.API.Public.TensorPack
public import NN.MLTheory.CROWN.Core
public import NN.MLTheory.CROWN.Graph
public import NN.Runtime.PyTorch.Import.Core
public import NN.Runtime.External.Process
public import NN.Verification.Robustness.TopLabel
public import NN.Verification.TorchLean.Compile
public import NN.Verification.Util.Json
import Lean.Data.Json

/-!
# Digits certified robustness

Certified accuracy for a linear classifier on sklearn's digits dataset.

Workflow:
- Train a small linear classifier on sklearn's digits (8x8) in Python and export:
  - weights JSON (`digits_linear_weights.json`)
  - test dataset JSON (`digits_test.json`)
- In Lean, load the weights + dataset and compute certified accuracy under an `ℓ∞` input box using:
  - IBP (`runIBP`)
  - a simple CROWN/affine pass (`runAffine` + `AffineVec.eval_on_box`)

Run:
  `lake exe verify -- digits`
  `lake exe verify -- digits --eps=0.02 --max=360`
  `lake exe verify -- digits --float32-mode ieee754exec --eps=0.02`
  `lake exe verify -- digits-train-certify --epochs=50 --eps=0.02 --max=100`

Regenerate assets:
  `python3 scripts/verification/robustness/train_digits_linear.py`
-/

@[expose] public section


namespace NN.Verification.Robustness.Digits

open _root_.Spec
open _root_.Spec.Tensor
open NN.API

open NN.MLTheory.CROWN.Graph
open NN.MLTheory.CROWN
open Import
open Lean
open Json
open NN.Verification.Json

/-- Flattened input dimension for sklearn digits (8×8). -/
def inDim : Nat := 64
/-- Number of classes (digits 0..9). -/
def outDim : Nat := 10

/-- Weight shape for a linear classifier `y = Wx + b` (10×64). -/
def WShape : Shape := .dim outDim (.dim inDim .scalar)
/-- Bias shape for a linear classifier (10). -/
def bShape : Shape := .dim outDim .scalar
/-- Input shape (64). -/
def xShape : Shape := .dim inDim .scalar
/-- Output/logit shape (10). -/
def yShape : Shape := .dim outDim .scalar

/-- Parameter shapes list used by the compiled TorchLean program (`[W, b]`). -/
def paramShapes : List Shape := [WShape, bShape]

/-- Bundled sklearn-digits linear classifier weights. -/
def defaultWeightsPath : String :=
  "NN/Examples/Verification/Robustness/digits_linear_weights.json"

/-- Bundled sklearn-digits test set. -/
def defaultDatasetPath : String :=
  "NN/Examples/Verification/Robustness/digits_test.json"

/-- Python exporter used by the train-then-certify command. -/
def defaultTrainScript : String :=
  "scripts/verification/robustness/train_digits_linear.py"

/-- CLI options for the digits certified-accuracy workflow. -/
structure DigitsOpts where
  /-- Weights JSON path (PyTorch export). -/
  weights : String := defaultWeightsPath
  /-- Dataset JSON path (PyTorch export). -/
  dataset : String := defaultDatasetPath
  /-- L∞ perturbation radius around each input example. -/
  eps     : Float  := 0.02
  /-- Max number of examples to evaluate (for local checks). -/
  max     : Nat    := 100
  deriving Repr

/-- Options for the train → compile → certify report command. -/
structure TrainCertifyOpts where
  /-- Lean-side certification options after Python exports the model and dataset. -/
  certify : DigitsOpts := {}
  /-- Python trainer script path. -/
  script : String := defaultTrainScript
  /-- Reproducibility seed forwarded to the trainer. -/
  seed : Nat := 0
  /-- Number of Python training epochs. -/
  epochs : Nat := 200
  /-- Python trainer batch size. -/
  batch : Nat := 128
  /-- Python trainer learning rate. -/
  lr : Float := 1e-2
  /-- Test split fraction used by the trainer. -/
  testSize : Float := 0.2
  /-- Number of test examples exported by the trainer. -/
  maxTest : Nat := 360
  deriving Repr

/-- Usage string printed on `--help` / `-h`. -/
def usage : String :=
  String.intercalate "\n" [
    "Usage:",
    ("  lake exe verify -- digits [--weights=PATH.json] " ++
      "[--dataset=PATH.json] [--eps=0.02] [--max=100]"),
    ("  lake exe verify -- digits-train-certify [trainer flags] " ++
      "[--weights=PATH.json] [--dataset=PATH.json] [--eps=0.02] [--max=100]"),
    "",
    "Notes:",
    "  - DType flags are also accepted (e.g. --float32-mode ieee754exec).",
    "  - digits-train-certify runs the Python trainer, then recompiles and certifies in Lean.",
    s!"  - Assets are generated by: python3 {defaultTrainScript}"
  ]

/-- Parse CLI args into `DigitsOpts` (returns `usage` as the error message on `--help`). -/
def parseArgs (args : List String) : Except String DigitsOpts := do
  let args := NN.API.CLI.dropDashDash args
  if NN.API.CLI.hasHelp args then
    throw usage
  let (weights, args) ← NN.API.CLI.takeFlagValueDefault args "weights" defaultWeightsPath
  let (dataset, args) ← NN.API.CLI.takeFlagValueDefault args "dataset" defaultDatasetPath
  let (eps, args) ← NN.API.CLI.takeFloatFlagDefault args "eps" 0.02
  let (max, args) ← NN.API.CLI.takeNatFlagDefault args "max" 100
  NN.API.CLI.requireNoArgs args
  pure { weights := weights, dataset := dataset, eps := eps, max := max }

/-- Parse the combined trainer/certifier CLI for `digits-train-certify`. -/
def parseTrainCertifyArgs (args : List String) : Except String TrainCertifyOpts := do
  let args := NN.API.CLI.dropDashDash args
  if NN.API.CLI.hasHelp args then
    throw usage
  let (script, args) ← NN.API.CLI.takeFlagValueDefault args "script" defaultTrainScript
  let (weights, args) ← NN.API.CLI.takeFlagValueDefault args "weights" defaultWeightsPath
  let (dataset, args) ← NN.API.CLI.takeFlagValueDefault args "dataset" defaultDatasetPath
  let (eps, args) ← NN.API.CLI.takeFloatFlagDefault args "eps" 0.02
  let (max, args) ← NN.API.CLI.takeNatFlagDefault args "max" 100
  let (seed, args) ← NN.API.CLI.takeNatFlagDefault args "seed" 0
  let (epochs, args) ← NN.API.CLI.takeNatFlagDefault args "epochs" 200
  let (batch, args) ← NN.API.CLI.takeNatFlagDefault args "batch" 128
  let (lr, args) ← NN.API.CLI.takeFloatFlagDefault args "lr" 1e-2
  let (testSize, args) ← NN.API.CLI.takeFloatFlagDefault args "test-size" 0.2
  let (maxTest, args) ← NN.API.CLI.takeNatFlagDefault args "max-test" 360
  NN.API.CLI.requireNoArgs args
  pure {
    certify := { weights := weights, dataset := dataset, eps := eps, max := max }
    script := script
    seed := seed
    epochs := epochs
    batch := batch
    lr := lr
    testSize := testSize
    maxTest := maxTest
  }

/-- Trainer command-line arguments generated from `TrainCertifyOpts`. -/
def trainerArgs (opts : TrainCertifyOpts) : Array String :=
  #[
    opts.script,
    "--seed", toString opts.seed,
    "--epochs", toString opts.epochs,
    "--lr", toString opts.lr,
    "--batch", toString opts.batch,
    "--test-size", toString opts.testSize,
    "--max-test", toString opts.maxTest,
    "--out-weights", opts.certify.weights,
    "--out-dataset", opts.certify.dataset
  ]

/-- TorchLean program for the linear classifier `y = Wx + b`. -/
def classifier {α : Type} [Context α] [DecidableEq Shape] :
    TorchLean.Program α (paramShapes ++ [xShape]) yShape :=
  fun {m} _ _ =>
    fun w b x =>
      (TorchLean.linear (m := m) (α := α) (inDim := inDim) (outDim := outDim) w b x
        : m (TorchLean.RefTy (m := m) (α := α) yShape))

/-- Load linear classifier weights exported from PyTorch into a typed `LinearSpec`. -/
def loadWeights (path : String) : IO (Spec.LinearSpec Float inDim outDim) := do
  let j ← readJsonObjectFile path
  match j with
  | .obj o =>
      let wJ ←
        match o.get? "layers.0.weight" with
        | some jw => pure jw
        | none => throw <| IO.userError "Missing weights key: layers.0.weight"
      let bJ ←
        match o.get? "layers.0.bias" with
        | some jb => pure jb
        | none => throw <| IO.userError "Missing weights key: layers.0.bias"
      let some wFn := Import.PyTorch.parseFloatMatrix outDim inDim wJ
        | throw <| IO.userError "layers.0.weight must be a float matrix of shape [10][64]"
      let some bFn := Import.PyTorch.parseFloatVec outDim bJ
        | throw <| IO.userError "layers.0.bias must be a float array of length 10"
      let w : Tensor Float WShape := Spec.matrixTensor wFn
      let b : Tensor Float bShape := Spec.vectorTensor bFn
      pure { weights := w, bias := b }
  | _ =>
      throw <| IO.userError "Weights JSON must be an object"

/-- Load the digits test dataset exported from Python (JSON). -/
def loadDataset (path : String) : IO (Array (Tensor Float xShape × Nat)) := do
  let j ← readJsonObjectFile path
  let examples ←
    match ← optionalField? j "examples" "dataset" with
    | none => pure #[]
    | some examplesJ => expectArray examplesJ "dataset.examples"
  let mut out : Array (Tensor Float xShape × Nat) := #[]
  for e in examples do
    let eo ← expectObj e "dataset example"
    let xJ ← expectField eo "x" "dataset example"
    let y ← expectFieldNat eo "y" "dataset example"
    let some vec := Import.PyTorch.parseFloatVec inDim xJ
      | throw <| IO.userError "Dataset example 'x' must be a float array of length 64"
    let xT : Tensor Float xShape := Spec.vectorTensor vec
    out := out.push (xT, y)
  pure out

/-- Running counters for the digits certified-accuracy workflow. -/
structure DigitsReport where
  /-- Number of examples checked. -/
  total : Nat := 0
  /-- Number of clean examples classified correctly by the exported model. -/
  nominalOk : Nat := 0
  /-- Number of examples certified by interval bound propagation. -/
  ibpOk : Nat := 0
  /-- Number of examples certified by the affine CROWN pass. -/
  crownOk : Nat := 0
  deriving Repr

/--
Run the certified-accuracy evaluation once, under a chosen scalar backend `α`.

This compiles the linear classifier to the verifier IR, then checks each example's `L∞` box using
IBP and a simple affine pass.
-/
def runOnce {α : Type} [Semantics.Scalar α] [DecidableEq Shape] [ToString α]
    [Runtime.Scalar α] (opts : DigitsOpts) : IO DigitsReport := do
  let cast : Float → α := Runtime.ofFloat
  let linF ← loadWeights opts.weights
  let examples0 ← loadDataset opts.dataset
  let examples := examples0.take opts.max

  let params : TensorPack α paramShapes :=
    tensorpack!
      (NN.API.Common.castTensor cast linF.weights),
      (NN.API.Common.castTensor cast linF.bias)

  let compiled ←
    match NN.Verification.TorchLean.compileForward1
          (α := α) (paramShapes := paramShapes) (inShape := xShape) (outShape := yShape)
          (classifier (α := α)) params with
    | .ok c => pure c
    | .error e => throw <| IO.userError e

  IO.println s!"[digits] compiled IR nodes: {compiled.graph.nodes.size}"

  let eps : α := cast opts.eps
  let rad : Tensor α xShape := Spec.fill (α := α) eps xShape
  let ctx : AffineCtx := { inputId := compiled.inputId, inputDim := inDim }

  let mut report : DigitsReport := {}

  for (xF, yNat) in examples do
    report := { report with total := report.total + 1 }

    let yF : Tensor Float yShape := Spec.linearSpec (α := Float) linF xF
    if (API.TorchLean.Metrics.argmax? (α := Float) (n := outDim) yF).map Fin.val = some yNat then
      report := { report with nominalOk := report.nominalOk + 1 }

    let x0 : Tensor α xShape := NN.API.Common.castTensor cast xF
    let loX := Tensor.clampSpec (Tensor.subSpec x0 rad) (0 : α) 1
    let hiX := Tensor.clampSpec (Tensor.addSpec x0 rad) (0 : α) 1
    let xB : FlatBox α :=
      { dim := inDim, lo := loX, hi := hiX }

    let ps : ParamStore α := compiled.seedInputBox xB

    let ibp := compiled.runIBP ps
    let outB ← compiled.outputBoxOrThrow ibp
    if hOut : outB.dim = outDim then
      let loY : Tensor α yShape := by
        simpa [yShape] using outB.loAsDim hOut
      let hiY : Tensor α yShape := by
        simpa [yShape] using outB.hiAsDim hOut
      if TopLabel.certifiesLabelFromTensorBounds (α := α) loY hiY yNat then
        report := { report with ibpOk := report.ibpOk + 1 }
    else
      throw <| IO.userError s!"Unexpected output dim {outB.dim} (expected {outDim})"

    let affs := runAffine (α := α) compiled.graph ps ctx ibp
    match compiled.outputAffine? affs with
    | .error _ =>
        -- Should not happen for linear/relu/linear graphs.
        pure ()
    | .ok outAff =>
      if hIn : outAff.inDim = inDim then
        if hOut : outAff.outDim = outDim then
            let outC := outAff.evalOnFlatBoxAsDim xB hIn.symm hOut
            let loY : Tensor α yShape := by
              simpa [yShape] using outC.lo
            let hiY : Tensor α yShape := by
              simpa [yShape] using outC.hi
            if TopLabel.certifiesLabelFromTensorBounds (α := α) loY hiY yNat then
              report := { report with crownOk := report.crownOk + 1 }
          else
            pure ()
        else
          pure ()

  IO.println s!"[digits] examples={report.total} eps={opts.eps}"
  IO.println s!"[digits] nominal accuracy: {report.nominalOk}/{report.total}"
  IO.println s!"[digits] certified (IBP):   {report.ibpOk}/{report.total}"
  IO.println s!"[digits] certified (CROWN): {report.crownOk}/{report.total}"
  pure report

/--
CLI entry point for the digits certified-robustness workflow.

This is wired into `lake exe verify -- digits`.
-/
def main (args : List String) : IO Unit := do
  IO.println "== TorchLean digits certified robustness =="
  let (dtype, rest) ←
    match NN.API.DType.parseAndStrip args with
    | .ok v => pure v
    | .error msg => throw <| IO.userError msg
  NN.API.DType.log dtype
  let opts ←
    match parseArgs rest with
    | .ok o => pure o
    | .error msg => throw <| IO.userError msg
  match (← NN.API.DType.withRuntime dtype (fun {α} _ _ _ _ => do
      let _ ← runOnce (α := α) opts
      pure ())) with
  | .ok () => pure ()
  | .error msg => throw <| IO.userError msg

/--
Train a fresh digits classifier, compile it through the TorchLean verifier path, and certify it.

The Python trainer is an artifact producer only.  Lean still parses the exported JSON, compiles the
TorchLean program to verifier IR, runs IBP and affine CROWN bounds, and prints the certification
report from the checked artifacts.
-/
def mainTrainThenCertify (args : List String) : IO Unit := do
  IO.println "== TorchLean digits train → compile → certify =="
  let (dtype, rest) ←
    match NN.API.DType.parseAndStrip args with
    | .ok v => pure v
    | .error msg => throw <| IO.userError msg
  NN.API.DType.log dtype
  let opts ←
    match parseTrainCertifyArgs rest with
    | .ok o => pure o
    | .error msg => throw <| IO.userError msg

  let pythonCmd ← Runtime.External.Process.resolveCmdFromEnv "TORCHLEAN_PYTHON" "python3"
  let python ← Runtime.External.Process.ensureCmdAvailable
    "Python 3" pythonCmd #["--version"] (some "TORCHLEAN_PYTHON")
  IO.println s!"[digits] training/export script: {opts.script}"
  IO.println s!"[digits] exported weights: {opts.certify.weights}"
  IO.println s!"[digits] exported dataset: {opts.certify.dataset}"
  let out ← Runtime.External.Process.runStdoutChecked
    (ctx := "digits train/export")
    (cmd := python)
    (args := trainerArgs opts)
    (cwd := some ".")
  let trainLog := out.trimAscii.toString
  if !trainLog.isEmpty then
    IO.println trainLog
  IO.println "[digits] Python export complete; entering Lean certification path."

  match (← NN.API.DType.withRuntime dtype (fun {α} _ _ _ _ => do
      let report ← runOnce (α := α) opts.certify
      if report.total = 0 then
        throw <| IO.userError "digits train-then-certify produced an empty report"
      IO.println
        (s!"[digits] report: total={report.total}, nominal={report.nominalOk}, " ++
          s!"ibp={report.ibpOk}, crown={report.crownOk}"))) with
  | .ok () => pure ()
  | .error msg => throw <| IO.userError msg

end NN.Verification.Robustness.Digits
