/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import NN.Verification.Robustness.MarginCert

/-!
# Bundled margin-certificate CLI

Command entry point for checking the bundled robustness margin certificate.  The JSON checker lives
in `NN.Verification.Robustness.MarginCert`; this module supplies the repository default artifact
path used by `lake exe verify -- margin-cert`.
-/

@[expose] public section

namespace NN.Verification.Robustness.MarginCertCLI

/-- Bundled certificate generated by the robustness export script. -/
def defaultPath : String :=
  "NN/Examples/Verification/Robustness/digits_linear_margin_cert.json"

/-- Check a margin certificate with timing disabled. -/
def check (path : String) : IO Unit :=
  NN.Verification.Robustness.MarginCert.check path

/-- Check a margin certificate with optional per-example timing. -/
def checkWithTiming (path : String) (timing : Bool) (timingEvery : Nat) : IO Unit :=
  NN.Verification.Robustness.MarginCert.checkWithTiming path timing timingEvery

/-- CLI entry point for `lake exe verify -- margin-cert [cert.json]`. -/
def run (args : List String) : IO Unit := do
  let usage :=
    String.intercalate "\n" [
      "Usage:",
      "  lake exe verify -- margin-cert [<path/to/cert.json>]",
      "",
      "If no path is provided, uses the bundled digits cert:",
      s!"  {defaultPath}",
      "",
      "To regenerate the cert:",
      "  python3 scripts/verification/robustness/export_margin_cert.py"
    ]

  if NN.API.CLI.hasHelp args then
    IO.println usage
    return

  NN.Verification.Robustness.MarginCert.runWithDefault defaultPath args

end NN.Verification.Robustness.MarginCertCLI
