/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import NN.Spec.Dynamics.System
public import NN.Spec.Layers.SelectiveScan

/-!
# State-space dynamical systems

State-space sequence models are recurrent dynamical systems:

`h_{t+1} = A_t h_t + B_t x_t`,
`y_t     = C_t h_t + D_t x_t`.

The full S4/Mamba family uses structured matrices and input-dependent ("selective") parameters.
This file starts with the diagonal/channelwise version because it is:

- the primitive implemented by a compact CUDA selective-scan kernel,
- enough to express the formal affine-scan algebra,
- and a useful educational baseline for examples.

The definitions reuse `DynamicalSystem` / `DrivenSystem` from
`NN/Spec/Dynamics/System.lean`, so existing notions such as `iterate`, `trajectory`,
`IsFixedPoint`, and `isContractive` apply immediately.
-/

@[expose] public section

namespace NN
namespace Spec
namespace Dynamics

open _root_.Spec

/--
A diagonal state-space model with elementwise input, state, and output channels.

This is the smallest useful SSM shape: it captures the recurrent memory path used by Mamba/S4 while
remaining easy to verify.  Richer models can wrap this core with linear projections and gates.
-/
structure DiagonalSSM (α : Type) (dim : Nat) where
  /-- Elementwise recurrent multiplier. Stability usually requires `|Aᵢ| < 1`. -/
  A : Tensor α (.dim dim .scalar)
  /-- Elementwise input-to-state gain. -/
  B : Tensor α (.dim dim .scalar)
  /-- Elementwise state-to-output gain. -/
  C : Tensor α (.dim dim .scalar)
  /-- Elementwise residual / skip gain. -/
  D : Tensor α (.dim dim .scalar)

namespace DiagonalSSM

variable {α : Type} [Add α] [Mul α] {dim : Nat}

/-- One recurrent state update `h' = A ⊙ h + B ⊙ x`. -/
def step (m : DiagonalSSM α dim)
    (h x : Tensor α (.dim dim .scalar)) : Tensor α (.dim dim .scalar) :=
  m.A * h + m.B * x

/-- Readout `y = C ⊙ h + D ⊙ x`. -/
def readout (m : DiagonalSSM α dim)
    (h x : Tensor α (.dim dim .scalar)) : Tensor α (.dim dim .scalar) :=
  m.C * h + m.D * x

/-- Convert a token vector into the corresponding affine transition for the hidden state. -/
def transition (m : DiagonalSSM α dim)
    (x : Tensor α (.dim dim .scalar)) : DiagonalTransition α dim :=
  { a := m.A, b := m.B * x }

/-- Applying the affine transition generated by `x` is exactly the SSM state update. -/
@[simp] theorem transition_apply_eq_step (m : DiagonalSSM α dim)
    (h x : Tensor α (.dim dim .scalar)) :
    (m.transition x).apply h = m.step h x := by
  rfl

/-- Run a full input sequence and return all hidden states. -/
def scan (m : DiagonalSSM α dim)
    (h0 : Tensor α (.dim dim .scalar))
    (xs : List (Tensor α (.dim dim .scalar))) :
    List (Tensor α (.dim dim .scalar)) :=
  diagonalSelectiveScan h0 (xs.map (fun x => m.transition x))

@[simp] theorem scan_nil (m : DiagonalSSM α dim)
    (h0 : Tensor α (.dim dim .scalar)) :
    m.scan h0 [] = [] := by
  rfl

@[simp] theorem scan_cons (m : DiagonalSSM α dim)
    (h0 x : Tensor α (.dim dim .scalar))
    (xs : List (Tensor α (.dim dim .scalar))) :
    m.scan h0 (x :: xs) = m.step h0 x :: m.scan (m.step h0 x) xs := by
  rfl

end DiagonalSSM

/--
View a scalar-specialized diagonal SSM recurrence as a `DrivenSystem`.

`DrivenSystem` uses TorchLean's default `SpecScalar`, while the reusable SSM record
above is polymorphic over scalar backends.  This adapter is the bridge to the existing dynamics API.
-/
def DiagonalSSM.drivenSystemSpecScalar {dim : Nat}
    (m : DiagonalSSM SpecScalar dim) : DrivenSystem (.dim dim .scalar) (.dim dim .scalar) where
  step := fun h x => m.step h x

@[simp] theorem DiagonalSSM.drivenSystemSpecScalar_step {dim : Nat}
    (m : DiagonalSSM SpecScalar dim)
    (h x : Tensor SpecScalar (.dim dim .scalar)) :
    (m.drivenSystemSpecScalar).step h x = m.step h x := by
  rfl

end Dynamics
end Spec
end NN
