name = "torchlean-blueprint"
defaultTargets = ["TorchLeanBlueprint", "blueprint-gen"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.32.0"

[[require]]
name = "subverso"
git = "https://github.com/leanprover/subverso"
rev = "0bd508e8362f56d4a05cbf63614d4c97db954041"

[[require]]
name = "TorchLean"
path = ".."
options = { cuda = "false" }

[[lean_lib]]
name = "TorchLeanBlueprint"

[[lean_exe]]
name = "blueprint-gen"
root = "TorchLeanBlueprintMain"
