/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import NN.API.Common
public import NN.API.Core
public import NN.API.Data
public import NN.Examples.Data.SamplePaths
public import NN.API.Data.Transforms
public import NN.API.Init
public import NN.API.Macros
public import NN.API.Public
public import NN.API.Runtime
public import NN.API.Samples
public import NN.API.Samples.Bands
public import NN.API.TList
public import NN.API.TorchLean.Optimizers
public import NN.API.TorchLean.Schedulers
public import NN.Entrypoint.Floats
public import NN.Entrypoint.GraphSpec
public import NN.Entrypoint.Proofs
public import NN.Entrypoint.Runtime
public import NN.Entrypoint.Spec
public import NN.Entrypoint.TorchLeanModels
public import NN.Examples.Zoo
public import NN.Examples.Advanced
public import NN.Verification.Cert.AbCrownLeafCert
public import NN.Verification.PINN.CLI
public import NN.Verification.PINN.Certificate
public import NN.Verification.PINN.Core
public import NN.Verification.PINN.DatasetCheck
public import NN.Verification.PINN.PdeAst
public import NN.Verification.PINN.PdeParse
public import NN.Verification.PINN.ResidualAffine
public import NN.Verification.ProofBackedCertificates
public import NN.Verification.Robustness.Digits
public import NN.Floats.Arb
public import NN.Floats.Arb.Oracle
public import NN.Floats.FP32
public import NN.Floats.FP32.Core
public import NN.Floats.FP32.Error
public import NN.Floats.FP32.Notation
public import NN.Floats.FP32.RuntimeApprox
public import NN.Floats.Float32
public import NN.Floats.IEEEExec
public import NN.Floats.IEEEExec.BridgeERealTotal
public import NN.Floats.IEEEExec.BridgeFP32
public import NN.Floats.IEEEExec.BridgeFP32Expr
public import NN.Floats.IEEEExec.BridgeFP32Total
public import NN.Floats.IEEEExec.BridgeInitFloat32
public import NN.Floats.IEEEExec.DirectedRoundingSoundness
public import NN.Floats.IEEEExec.DivDirectedRoundingSoundness
public import NN.Floats.IEEEExec.ERealSemantics
public import NN.Floats.IEEEExec.Exec32
public import NN.Floats.IEEEExec.MinMaxERealSoundness
public import NN.Floats.IEEEExec.MkBitsToReal
public import NN.Floats.IEEEExec.NatLemmas
public import NN.Floats.IEEEExec.Notation
public import NN.Floats.IEEEExec.Reductions
public import NN.Floats.IEEEExec.RoundDyadicToIEEE32Bounds
public import NN.Floats.IEEEExec.RoundQuotEvenBounds
public import NN.Floats.IEEEExec.RoundShiftRightEven
public import NN.Floats.IEEEExec.SpecialRules
public import NN.Floats.IEEEExec.TranscendentalRules
public import NN.Floats.Interval
public import NN.Floats.Interval.FP32
public import NN.Floats.Interval.IEEEExec32
public import NN.Floats.Interval.IEEEExec32AddSoundness
public import NN.Floats.Interval.IEEEExec32ArbTrans
public import NN.Floats.Interval.IEEEExec32DivSoundness
public import NN.Floats.Interval.IEEEExec32MinMaxSoundness
public import NN.Floats.Interval.IEEEExec32MulSoundness
public import NN.Floats.Interval.IEEEExec32NoNaN
public import NN.Floats.Interval.Quantized
public import NN.Floats.Interval.RealBounds
public import NN.Floats.Interval.Rounders
public import NN.Floats.NeuralFloat
public import NN.Floats.NeuralFloat.Conversion
public import NN.Floats.NeuralFloat.Core
public import NN.Floats.NeuralFloat.ErrorBounds
public import NN.Floats.NeuralFloat.Formats
public import NN.Floats.NeuralFloat.Metadata
public import NN.Floats.NeuralFloat.NF
public import NN.Floats.NeuralFloat.NNOps
public import NN.Floats.NeuralFloat.Rounding
public import NN.Entrypoint.GraphSpec
public import NN.Entrypoint.IR
public import NN.MLTheory.API
public import NN.MLTheory.CROWN.BoundOps
public import NN.MLTheory.CROWN.Cert.AlphaBetaCROWN
public import NN.MLTheory.CROWN.Cert.AlphaCROWN
public import NN.MLTheory.CROWN.Core
public import NN.MLTheory.CROWN.Extras.AlphaConfig
public import NN.MLTheory.CROWN.Extras.BoundOpsIEEE32Exec
public import NN.MLTheory.CROWN.Extras.FP32
public import NN.MLTheory.CROWN.Extras.FloatIntegration
public import NN.MLTheory.CROWN.Extras.IntervalLemmas
public import NN.MLTheory.CROWN.Flatbox
public import NN.MLTheory.CROWN.Graph
public import NN.MLTheory.CROWN.Lyapunov.TwoStage.Core
public import NN.MLTheory.CROWN.Lyapunov.TwoStage.ExecUtils
public import NN.MLTheory.CROWN.Lyapunov.Verification
public import NN.MLTheory.CROWN.Models.Mlp
public import NN.MLTheory.CROWN.Operators
public import NN.MLTheory.CROWN.Operators.Activations
public import NN.MLTheory.CROWN.Operators.Arithmetic
public import NN.MLTheory.CROWN.Operators.Batchnorm
public import NN.MLTheory.CROWN.Operators.Conv
public import NN.MLTheory.CROWN.Operators.Gelu
public import NN.MLTheory.CROWN.Operators.Pooling
public import NN.MLTheory.CROWN.Operators.Reduce
public import NN.MLTheory.CROWN.Operators.Slice
public import NN.MLTheory.CROWN.Operators.Trigonometric
public import NN.MLTheory.CROWN.Proofs.AlphaBetaReLUScalarSoundness
public import NN.MLTheory.CROWN.Proofs.Distillation
public import NN.MLTheory.CROWN.Proofs.GraphAlphaCrownTransferSoundness
public import NN.MLTheory.CROWN.Proofs.GraphCertSoundness
public import NN.MLTheory.CROWN.Proofs.GraphCrownCertSoundness
public import NN.MLTheory.CROWN.Proofs.GraphIBPBasicTheorems
public import NN.MLTheory.CROWN.Proofs.GraphRunibpEndToEnd
public import NN.MLTheory.CROWN.Proofs.Overview
public import NN.MLTheory.CROWN.Proofs.SoundnessProofs
public import NN.MLTheory.CROWN.Propagation.Backward
public import NN.MLTheory.CROWN.Propagation.LinearSignsplit
public import NN.MLTheory.CROWN.Runtime.Ops
public import NN.MLTheory.CROWN.Tactics.CrownOracle
public import NN.MLTheory.LearningTheory.DifferentialPrivacy.Core
public import NN.MLTheory.LearningTheory.Robustness.Runtime
public import NN.MLTheory.LearningTheory.Robustness.Spec
public import NN.MLTheory.LearningTheory.Stability.Core
public import NN.MLTheory.LearningTheory.Stability.Dynamics.Runtime
public import NN.MLTheory.LearningTheory.Stability.Dynamics.Spec
public import NN.MLTheory.LearningTheory.Stability.RidgeRegression1D
public import NN.MLTheory.LearningTheory.Stability.RidgeRegression1D.IEEE32Exec
public import NN.MLTheory.LearningTheory.Stability.RidgeRegression1D.IEEE32Exec.Core
public import NN.MLTheory.LearningTheory.Stability.RidgeRegression1D.IEEE32Exec.ExampleDataset
public import NN.MLTheory.LearningTheory.Stability.RidgeRegression1D.Real
public import NN.MLTheory.Proofs.Approximation.FloatInterval.ConstantTarget
public import NN.MLTheory.Proofs.Approximation.FloatInterval.ExactImageTheorem
public import NN.MLTheory.Proofs.Approximation.FloatInterval.Semantics
public import NN.MLTheory.Proofs.Approximation.Universal.IEEE32ExecCore
public import NN.MLTheory.Proofs.Approximation.Universal.UniversalApproximation
public import NN.MLTheory.Proofs.Approximation.Universal.UniversalApproximationFP32
public import NN.MLTheory.Proofs.Approximation.Universal.UniversalApproximationIEEE32Exec
public import NN.MLTheory.Proofs.Approximation.Universal.UniversalApproximationIEEE32ExecMlp2
public import NN.MLTheory.Proofs.Approximation.Universal.UniversalApproximationND
public import NN.MLTheory.Proofs.Hopfield.Basic
public import NN.MLTheory.Proofs.Hopfield.Convergence
public import NN.MLTheory.Proofs.Hopfield.Dynamics
public import NN.MLTheory.Proofs.Hopfield.Energy
public import NN.MLTheory.Proofs.Hopfield.Progress
public import NN.MLTheory.Proofs.ReLU.Approx.ReLUMulApprox
public import NN.MLTheory.Proofs.ReLU.Bridge.ReLUMlpBridge
public import NN.MLTheory.Proofs.ReLU.Approximation.CompactSet
public import NN.MLTheory.Proofs.StateSpace.Scan
public import NN.MLTheory.Proofs.Verification.Robustness.MlpRobustness
public import NN.Proofs.Analysis
public import NN.Proofs.Autograd.Coverage
public import NN.Proofs.Autograd.Core.RealCorrectness
public import NN.Proofs.Autograd.Core.SemiringCorrectness
public import NN.Proofs.Autograd.Core.Vectorization
public import NN.Proofs.Autograd.FDeriv.Core
public import NN.Proofs.Autograd.FDeriv.Elementwise
public import NN.Proofs.Autograd.FDeriv.LogSoftmax
public import NN.Proofs.Autograd.FDeriv.MlpMse
public import NN.Proofs.Autograd.FDeriv.OpSpec
public import NN.Proofs.Autograd.FDeriv.Params
public import NN.Proofs.Autograd.FDeriv.Softmax
public import NN.Proofs.Autograd.Notation
public import NN.Proofs.Autograd.Overview
public import NN.Proofs.Autograd.Runtime.Link
public import NN.Proofs.Autograd.Tape.Algebra.Nodes
public import NN.Proofs.Autograd.Tape.Algebra.Soundness
public import NN.Proofs.Autograd.Tape.Core.FDeriv
public import NN.Proofs.Autograd.Tape.Core.Soundness
public import NN.Proofs.Autograd.Tape.Nodes
public import NN.Proofs.Autograd.Tape.Nodes.Batched
public import NN.Proofs.Autograd.Tape.Nodes.Shape
public import NN.Proofs.Autograd.Tape.Ops.Attention.MultiHeadSelfAttention
public import NN.Proofs.Autograd.Tape.Ops.Attention.ScaledDotProduct
public import NN.Proofs.Autograd.Tape.Ops.Conv.BackwardDot
public import NN.Proofs.Autograd.Tape.Ops.Conv.FDeriv
public import NN.Proofs.Autograd.Tape.Ops.Embedding.GatherRows
public import NN.Proofs.Autograd.Tape.Ops.Norm.BatchNormChannelFirst
public import NN.Proofs.Autograd.Tape.Ops.Norm.LayerNorm
public import NN.Proofs.Autograd.Tape.Util.Idx
public import NN.Proofs.Autograd.Training.StepAlgebra
public import NN.Proofs.Gradients.Activation
public import NN.Proofs.Gradients.Linear
public import NN.Proofs.RuntimeApprox
public import NN.Proofs.Tensor
public import NN.Proofs.Verification
public import NN.Runtime.Autograd.Compiled
public import NN.Runtime.Autograd.Engine
public import NN.Runtime.Autograd.Overview
public import NN.Runtime.Autograd.Torch
public import NN.Runtime.Autograd.TorchLean
public import NN.Runtime.Autograd.TorchLean.Autodiff
public import NN.Runtime.Autograd.TorchLean.Backend
public import NN.Runtime.Autograd.TorchLean.CompileExec
public import NN.Runtime.Autograd.TorchLean.Dual
public import NN.Runtime.Autograd.TorchLean.Fno1d
public import NN.Runtime.Autograd.TorchLean.Functional
public import NN.Runtime.Autograd.TorchLean.Loss
public import NN.Runtime.Autograd.TorchLean.Metrics
public import NN.Runtime.Autograd.TorchLean.Module
public import NN.Runtime.Autograd.TorchLean.NN
public import NN.Runtime.Autograd.TorchLean.Norm
public import NN.Runtime.Autograd.TorchLean.Optim
public import NN.Runtime.Autograd.TorchLean.Random
public import NN.Runtime.Autograd.TorchLean.Session
public import NN.Runtime.Autograd.Train
public import NN.Runtime.Autograd.Utils
public import NN.Runtime.Context
public import NN.Runtime.Optim
public import NN.Runtime.PyTorch
public import NN.Runtime.Scalar
public import NN.Runtime.Training.Log
public import NN.Runtime.Variable
public import NN.Spec.Autograd.AutogradSpec
public import NN.Spec.Autograd.Ops
public import NN.Spec.Core.Context
public import NN.Spec.Core.Scalar
public import NN.Spec.Core.Sequence
public import NN.Spec.Core.Shape
public import NN.Spec.Core.Tensor
public import NN.Spec.Core.Tensor.Constructors
public import NN.Spec.Core.Tensor.Core
public import NN.Spec.Core.Tensor.Linalg
public import NN.Spec.Core.Tensor.Vec
public import NN.Spec.Core.TensorArray
public import NN.Spec.Core.TensorBridge
public import NN.Spec.Core.TensorGrad
public import NN.Spec.Core.TensorOps
public import NN.Spec.Core.TensorReductionShape
public import NN.Spec.Core.Utils
public import NN.Spec.Dynamics.System
public import NN.Spec.Dynamics.StateSpace
public import NN.Spec.Layers.Activation
public import NN.Spec.Layers.Attention
public import NN.Spec.Layers.Conv
public import NN.Spec.Layers.Dropout
public import NN.Spec.Layers.Embedding
public import NN.Spec.Layers.FlashAttention
public import NN.Spec.Layers.GlobalPooling
public import NN.Spec.Layers.Gnn
public import NN.Spec.Layers.Gru
public import NN.Spec.Layers.Linear
public import NN.Spec.Layers.Loss
public import NN.Spec.Layers.Lstm
public import NN.Spec.Layers.Normalization
public import NN.Spec.Layers.Pooling
public import NN.Spec.Layers.PositionalEncoding
public import NN.Spec.Layers.Rnn
public import NN.Spec.Layers.SelectiveScan
public import NN.Spec.Layers.Utils
public import NN.Spec.Models.Autoencoder
public import NN.Spec.Models.Cnn
public import NN.Spec.Models.CommonHelpers
public import NN.Spec.Models.Gmm
public import NN.Spec.Models.Gnn
public import NN.Spec.Models.GradientBoostedTrees
public import NN.Spec.Models.Hmm
public import NN.Spec.Models.Hopfield
public import NN.Spec.Models.Knn
public import NN.Spec.Models.LinearRegression
public import NN.Spec.Models.LogisticRegression
public import NN.Spec.Models.Mamba
public import NN.Spec.Models.Mlp
public import NN.Spec.Models.NaiveBayes
public import NN.Spec.Models.Pca
public import NN.Spec.Models.RandomForest
public import NN.Spec.Models.Resnet
public import NN.Spec.Models.S4
public import NN.Spec.Models.Seq2seq
public import NN.Spec.Models.Svm
public import NN.Spec.Models.Transformer
public import NN.Spec.Models.Unet
public import NN.Spec.Models.Vit
public import NN.Spec.Module.Activation
public import NN.Spec.Module.Attention
public import NN.Spec.Module.Autoencoder
public import NN.Spec.Module.Conv
public import NN.Spec.Module.DecisionTree
public import NN.Spec.Module.Dropout
public import NN.Spec.Module.Embedding
public import NN.Spec.Module.Flatten
public import NN.Spec.Module.GlobalPooling
public import NN.Spec.Module.Gmm
public import NN.Spec.Module.Gnn
public import NN.Spec.Module.GradientBoostedTrees
public import NN.Spec.Module.GruModels
public import NN.Spec.Module.Hmm
public import NN.Spec.Module.Linear
public import NN.Spec.Module.LinearRegression
public import NN.Spec.Module.LogisticRegression
public import NN.Spec.Module.LstmModels
public import NN.Spec.Module.Normalization
public import NN.Spec.Module.Pca
public import NN.Spec.Module.Pooling
public import NN.Spec.Module.PositionalEncoding
public import NN.Spec.Module.Resnet
public import NN.Spec.Module.Rnn
public import NN.Spec.Module.RnnModels
public import NN.Spec.Module.Seq2seq
public import NN.Spec.Module.SpecModule
public import NN.Spec.Module.Svm
public import NN.Entrypoint.Tensor
public import NN.Tests.Runtime.Floats.AllAutogradTests
public import NN.Tests.Runtime.Floats.KnnCheck
public import NN.Tests.Runtime.Floats.ModelsCheck
public import NN.Tests.Runtime.Floats.PINNDerivResidual
public import NN.Tests.Runtime.Floats.RnnGruLstmBpttCheck
public import NN.Tests.Runtime.Floats.Suite
public import NN.Tests.Runtime.Floats.TorchLeanIRExecEquivCheck
public import NN.Tests.Runtime.Floats.TorchLeanIndexShapeCheck
public import NN.Tests.Runtime.Floats.TorchLeanOpsCheck
public import NN.Tests.Runtime.Floats.TorchLeanSpecMlpEquivCheck
public import NN.Tests.Runtime.Floats.Utils
public import NN.Tests.Runtime.Rationals.AutogradEngineTest
public import NN.Tests.Runtime.Rationals.MlpTest
public import NN.Tests.Runtime.Rationals.Suite
public import NN.Verification.Cert.CROWNNodeCert
public import NN.Verification.Cert.CROWNNodeCertAlphaBeta
public import NN.Verification.Cert.IBPCert
public import NN.Verification.Cert.IBPNodeCert
public import NN.Verification.ODE.Ast
public import NN.Verification.ODE.Parse
public import NN.Verification.PINN.Architecture
public import NN.Verification.TorchLean.Compile
public import NN.Verification.TorchLean.CompileExec
public import NN.Verification.TorchLean.Correctness
public import NN.Verification.TorchLean.Verified
public import NN.Verification.TorchLean.SpecEval
public import NN.Verification.Util.FloatApprox
public import NN.Verification.Util.Json
public import NN.Entrypoint.Widgets

/-!
CI-facing import sweep.

This file imports the public and internal surfaces that should remain buildable together in the
continuous-integration configuration.
-/

/-!
# All

CI-only umbrella: import (almost) everything under `NN/`.

This module exists for CI. It pulls in the full library plus the curated examples so we can
catch “works in one corner but not the other” breakage early.

Developer tooling may refresh this file as new modules are added.

What’s excluded:
- A handful of *very slow* proofs (build them explicitly when you want CI coverage).
- Any module that defines a top-level `main` (importing two executable roots into the same
  environment causes a `main` name clash). Those are checked by building `lake exe …` targets
  directly instead.

Local usage (slow):
- `lake build NN.CI.All`

Please don’t import this from user-facing modules (`import NN`).
-/

@[expose] public section
