/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import NN.Runtime.Autograd.TorchLean.Session.Types

/-!
# Session Tensor Operations

This file is the shared eager/compiled dispatch layer for elementary tensor operations. It keeps the
public `Session` API uniform while routing each operation to either the eager tape backend or the
compiled SSA/IR session.
-/

@[expose] public section

namespace Runtime
namespace Autograd
namespace TorchLean

open Spec
open Tensor

namespace Session

/-- Elementwise addition (dispatches to eager vs compiled backend). -/
def add {α : Type} (s : Session α) [Add α] [Zero α] [DecidableEq Shape] {sh : Shape}
  (a b : _root_.Runtime.Autograd.Torch.TensorRef α sh) : IO (_root_.Runtime.Autograd.Torch.TensorRef
    α sh) := do
  match s.impl with
  | .eager sess => EagerSession.add (α := α) sess (sh := sh) a b
  | .compiled sess =>
      _root_.Runtime.Autograd.Torch.Internal.SessionIR.add (α := α) sess (sh := sh) a b

/-- Elementwise subtraction (dispatches to eager vs compiled backend). -/
def sub {α : Type} (s : Session α) [Sub α] [Add α] [Zero α] [DecidableEq Shape] {sh : Shape}
  (a b : _root_.Runtime.Autograd.Torch.TensorRef α sh) : IO (_root_.Runtime.Autograd.Torch.TensorRef
    α sh) := do
  match s.impl with
  | .eager sess => EagerSession.sub (α := α) sess (sh := sh) a b
  | .compiled sess =>
      _root_.Runtime.Autograd.Torch.Internal.SessionIR.sub (α := α) sess (sh := sh) a b

/-- Elementwise multiplication (dispatches to eager vs compiled backend). -/
def mul {α : Type} (s : Session α) [Mul α] [Add α] [Zero α] [DecidableEq Shape] {sh : Shape}
  (a b : _root_.Runtime.Autograd.Torch.TensorRef α sh) : IO (_root_.Runtime.Autograd.Torch.TensorRef
    α sh) := do
  match s.impl with
  | .eager sess => EagerSession.mul (α := α) sess (sh := sh) a b
  | .compiled sess =>
      _root_.Runtime.Autograd.Torch.Internal.SessionIR.mul (α := α) sess (sh := sh) a b

/--
Scale a tensor by a scalar constant `c` (elementwise).

PyTorch analogy: `x * c` or `torch.mul(x, c)`.
-/
def scale {α : Type} (s : Session α) [Mul α] [Add α] [Zero α] [DecidableEq Shape]
  [_root_.Runtime.Autograd.Torch.Internal.CudaBridge.TensorConv α] {sh : Shape}
  (x : _root_.Runtime.Autograd.Torch.TensorRef α sh) (c : α) :
  IO (_root_.Runtime.Autograd.Torch.TensorRef α sh) := do
  match s.impl with
  | .eager sess => EagerSession.scale (α := α) sess (sh := sh) x c
  | .compiled sess =>
      _root_.Runtime.Autograd.Torch.Internal.SessionIR.scale (α := α) sess (sh := sh) x c

/--
Dropout implemented as a Session-level derived op.

In training mode, this records:

`y = x * mask / (1 - p)`

where `mask : {0,1}` is generated by the Torch primitive `bernoulli_mask`.

## RNG Semantics (JAX-style / functional RNG)

Randomness is a deterministic function of explicit session state:
- we read `(seed, counter)` from the session-level `RngState`,
- derive a per-call `opSeed` deterministically, and
- advance the `RngState` (update `seed`, increment `counter`).

Important: the `bernoulli_mask` op also mixes in a backend-internal counter (approximately: current tape
size / node index). So even with the same `RngState`, changing the surrounding graph structure can
change the exact samples. This is still fully deterministic for a fixed graph.

In evaluation mode (`train=false`), this is the identity.

`p` is expected to satisfy `0 ≤ p < 1`; we throw if `keepProb = 1 - p` is not strictly positive.
-/
def dropout {α : Type} [Context α] [DecidableEq Shape]
    [_root_.Runtime.Autograd.Torch.Internal.CudaBridge.TensorConv α]
    (s : Session α) (rng : RngState) {sh : Shape}
    (x : _root_.Runtime.Autograd.Torch.TensorRef α sh)
    (p : α) (train : Bool := true) :
    IO (_root_.Runtime.Autograd.Torch.TensorRef α sh) := do
  if !train then
    pure x
  else
    let keepProb : α := (1 : α) - p
    have : Decidable (keepProb > (0 : α)) := (Context.decidable_gt) keepProb 0
    if _h : keepProb > (0 : α) then
      let seedNat ← getNat (α := α) s rng.seed
      let ctrNat ← getNat (α := α) s rng.counter
      -- Seed is derived deterministically from the explicit `(seed, counter)` state.
      -- Note: `Torch.bernoulli_mask` also mixes in an internal per-graph counter (tape size / node
      -- index), so graph structure can affect the exact samples even with the same `RngState`.
      let opSeed := Random.nextSeed seedNat ctrNat
      setNat (α := α) s rng.seed opSeed
      setNat (α := α) s rng.counter (ctrNat + 1)

      let keepProbRef ← const (α := α) s (sh := Shape.scalar) (Tensor.scalar keepProb)
      let maskRef ←
        match s.impl with
        | .eager sess =>
            _root_.Runtime.Autograd.Torch.Internal.EagerSession.bernoulliMask (α := α) sess.inner
              (sh := sh) keepProbRef opSeed
        | .compiled sess =>
            _root_.Runtime.Autograd.Torch.Internal.SessionIR.commitGraphM (α := α) sess
              (β := _root_.Runtime.Autograd.Torch.TensorRef α sh) (fun {Γ} {ss} xv nat g => do
                let (v, st') ← _root_.Runtime.Autograd.Torch.Internal.SessionIR.runGraphM (α := α)
                  (Γ := Γ)
                  (Runtime.Autograd.Compiled.GraphM.bernoulliMask (α := α) (Γ := Γ) (s := sh)
                    { id := keepProbRef.id } (seed := opSeed))
                  ss g
                let ⟨ss', g'⟩ := st'
                let st1 : _root_.Runtime.Autograd.Torch.Internal.SessionIRState α :=
                  { Γ := Γ, x := xv, nat := nat, ss := ss', g := g' }
                pure ({ id := v.id }, st1))

      let y ← mul (α := α) s (sh := sh) x maskRef
      let invKeep : α := (1 : α) / keepProb
      scale (α := α) s (sh := sh) y invKeep
    else
      throw <| IO.userError "dropout: expected (1 - p) > 0"

/-- Elementwise absolute value (dispatches to eager vs compiled backend). -/
def abs {α : Type} (s : Session α) [Context α] [DecidableRel ((· > ·) : α → α → Prop)] [DecidableEq
  Shape]
  {sh : Shape} (x : _root_.Runtime.Autograd.Torch.TensorRef α sh) :
  IO (_root_.Runtime.Autograd.Torch.TensorRef α sh) := do
  match s.impl with
  | .eager sess => EagerSession.abs (α := α) sess (sh := sh) x
  | .compiled sess =>
      _root_.Runtime.Autograd.Torch.Internal.SessionIR.abs (α := α) sess (sh := sh) x

/-- Elementwise square root (dispatches to eager vs compiled backend). -/
def sqrt {α : Type} (s : Session α) [Context α] [DecidableRel ((· > ·) : α → α → Prop)] [DecidableEq
  Shape]
  {sh : Shape} (x : _root_.Runtime.Autograd.Torch.TensorRef α sh) :
  IO (_root_.Runtime.Autograd.Torch.TensorRef α sh) := do
  match s.impl with
  | .eager sess => EagerSession.sqrt (α := α) sess (sh := sh) x
  | .compiled sess =>
      _root_.Runtime.Autograd.Torch.Internal.SessionIR.sqrt (α := α) sess (sh := sh) x

/-- Elementwise clamp to `[minVal, maxVal]` (dispatches to eager vs compiled backend). -/
def clamp {α : Type} (s : Session α) [Context α] [DecidableRel ((· > ·) : α → α → Prop)]
  [DecidableEq Shape]
  [_root_.Runtime.Autograd.Torch.Internal.CudaBridge.TensorConv α]
  {sh : Shape} (x : _root_.Runtime.Autograd.Torch.TensorRef α sh) (minVal maxVal : α) :
  IO (_root_.Runtime.Autograd.Torch.TensorRef α sh) := do
  match s.impl with
  | .eager sess => EagerSession.clamp (α := α) sess (sh := sh) x minVal maxVal
  | .compiled sess =>
      _root_.Runtime.Autograd.Torch.Internal.SessionIR.clamp (α := α) sess
        (sh := sh) x minVal maxVal

/-- Elementwise maximum (dispatches to eager vs compiled backend). -/
def max {α : Type} (s : Session α) [Context α] [DecidableRel ((· > ·) : α → α → Prop)] [DecidableEq
  Shape]
  {sh : Shape} (a b : _root_.Runtime.Autograd.Torch.TensorRef α sh) :
  IO (_root_.Runtime.Autograd.Torch.TensorRef α sh) := do
  match s.impl with
  | .eager sess => EagerSession.max (α := α) sess (sh := sh) a b
  | .compiled sess =>
      _root_.Runtime.Autograd.Torch.Internal.SessionIR.max (α := α) sess (sh := sh) a b

/-- Elementwise minimum (dispatches to eager vs compiled backend). -/
def min {α : Type} (s : Session α) [Context α] [DecidableRel ((· > ·) : α → α → Prop)] [DecidableEq
  Shape]
  {sh : Shape} (a b : _root_.Runtime.Autograd.Torch.TensorRef α sh) :
  IO (_root_.Runtime.Autograd.Torch.TensorRef α sh) := do
  match s.impl with
  | .eager sess => EagerSession.min (α := α) sess (sh := sh) a b
  | .compiled sess =>
      _root_.Runtime.Autograd.Torch.Internal.SessionIR.min (α := α) sess (sh := sh) a b

/--
Matrix multiplication (rank-2 tensors).

PyTorch analogy: `torch.matmul` / `@` for matrices.
-/
def matmul {α : Type} (s : Session α) [Context α] [DecidableEq Shape]
  {m n p : Nat}
  (a : _root_.Runtime.Autograd.Torch.TensorRef α (.dim m (.dim n .scalar)))
  (b : _root_.Runtime.Autograd.Torch.TensorRef α (.dim n (.dim p .scalar))) :
  IO (_root_.Runtime.Autograd.Torch.TensorRef α (.dim m (.dim p .scalar))) := do
  match s.impl with
  | .eager sess => EagerSession.matmul (α := α) sess (m := m) (n := n) (p := p) a b
  | .compiled sess =>
      _root_.Runtime.Autograd.Torch.Internal.SessionIR.matmul (α := α) sess
        (m := m) (n := n) (p := p) a b

/--
Batched matrix multiplication (rank-3 tensors).

PyTorch analogy: `torch.bmm`.
-/
def bmm {α : Type} (s : Session α) [Add α] [Mul α] [Zero α] [DecidableEq Shape]
  {batch m n p : Nat}
  (a : _root_.Runtime.Autograd.Torch.TensorRef α (.dim batch (.dim m (.dim n .scalar))))
  (b : _root_.Runtime.Autograd.Torch.TensorRef α (.dim batch (.dim n (.dim p .scalar)))) :
  IO (_root_.Runtime.Autograd.Torch.TensorRef α (.dim batch (.dim m (.dim p .scalar)))) := do
  match s.impl with
  | .eager sess => EagerSession.bmm (α := α) sess (batch := batch) (m := m) (n := n) (p := p) a b
  | .compiled sess =>
      _root_.Runtime.Autograd.Torch.Internal.SessionIR.bmm (α := α) sess (batch := batch) (m := m)
        (n := n) (p := p) a b

/-- Concatenate two vectors along dimension 0 (dispatches to eager vs compiled backend). -/
def concatVectors {α : Type} (s : Session α) [Context α] [DecidableEq Shape]
  {n m : Nat}
  (a : _root_.Runtime.Autograd.Torch.TensorRef α (.dim n .scalar))
  (b : _root_.Runtime.Autograd.Torch.TensorRef α (.dim m .scalar)) :
  IO (_root_.Runtime.Autograd.Torch.TensorRef α (.dim (n + m) .scalar)) := do
  match s.impl with
  | .eager sess => EagerSession.concatVectors (α := α) sess (n := n) (m := m) a b
  | .compiled sess =>
      _root_.Runtime.Autograd.Torch.Internal.SessionIR.concatVectors (α := α) sess
        (n := n) (m := m) a b

/-- Concatenate along the outermost dimension (dimension 0) (dispatches to eager vs compiled
  backend). -/
def concatLeadingAxis {α : Type} (s : Session α) [Context α] [DecidableEq Shape]
  {n m : Nat} {sh : Shape}
  (a : _root_.Runtime.Autograd.Torch.TensorRef α (.dim n sh))
  (b : _root_.Runtime.Autograd.Torch.TensorRef α (.dim m sh)) :
  IO (_root_.Runtime.Autograd.Torch.TensorRef α (.dim (n + m) sh)) := do
  match s.impl with
  | .eager sess => EagerSession.concatLeadingAxis (α := α) sess (n := n) (m := m) (sh := sh) a b
  | .compiled sess =>
      _root_.Runtime.Autograd.Torch.Internal.SessionIR.concatLeadingAxis (α := α) sess (n := n) (m := m)
        (sh := sh) a b

/--
Slice a contiguous `[start, start+len)` range from dimension 0.

PyTorch analogy: `x[start:start+len]` for the first dimension.
-/
def sliceLeadingAxisRange {α : Type} (s : Session α) [Zero α] [DecidableEq Shape]
  {n : Nat} {sh : Shape}
  (x : _root_.Runtime.Autograd.Torch.TensorRef α (.dim n sh)) (start len : Nat) (h : len + start ≤
    n) :
  IO (_root_.Runtime.Autograd.Torch.TensorRef α (.dim len sh)) := do
  match s.impl with
  | .eager sess => EagerSession.sliceLeadingAxisRange (α := α) sess (n := n) (sh := sh) x start len h
  | .compiled sess =>
      _root_.Runtime.Autograd.Torch.Internal.SessionIR.sliceLeadingAxisRange (α := α) sess
        (n := n) (sh := sh) x start len h

/--
2D max pooling on a CHW tensor.

PyTorch analogy: `torch.nn.functional.max_pool2d` (channel-first layout).
-/
def maxPool2d {α : Type} (s : Session α) [Context α] [DecidableEq Shape]
  {kH kW inH inW inC stride : Nat} {h1 : kH ≠ 0} {h2 : kW ≠ 0}
  (x : _root_.Runtime.Autograd.Torch.TensorRef α (.dim inC (.dim inH (.dim inW .scalar)))) :
  IO (_root_.Runtime.Autograd.Torch.TensorRef α
    (.dim inC (.dim (Spec.Shape.slidingWindowOutDim inH kH stride 0) (.dim (Spec.Shape.slidingWindowOutDim inW kW stride 0) .scalar)))) := do
  match s.impl with
  | .eager sess =>
      EagerSession.maxPool2d (α := α) sess (kH := kH) (kW := kW) (inH := inH) (inW := inW)
        (inC := inC) (stride := stride) (h1 := h1) (h2 := h2) x
  | .compiled sess =>
      _root_.Runtime.Autograd.Torch.Internal.SessionIR.maxPool2d (α := α) sess
        (kH := kH) (kW := kW) (inH := inH) (inW := inW) (inC := inC) (stride := stride)
        (h1 := h1) (h2 := h2) x

/--
Smooth max pooling (differentiable surrogate for max pooling) on a CHW tensor.

This is parameterized by `beta` (larger values behave more like true max pooling).
-/
def smoothMaxPool2d {α : Type} (s : Session α) [Context α] [DecidableEq Shape]
  [_root_.Runtime.Autograd.Torch.Internal.CudaBridge.TensorConv α]
  {kH kW inH inW inC stride : Nat} {h1 : kH ≠ 0} {h2 : kW ≠ 0}
  (x : _root_.Runtime.Autograd.Torch.TensorRef α (.dim inC (.dim inH (.dim inW .scalar)))) (beta :
    α) :
  IO (_root_.Runtime.Autograd.Torch.TensorRef α
    (.dim inC (.dim (Spec.Shape.slidingWindowOutDim inH kH stride 0) (.dim (Spec.Shape.slidingWindowOutDim inW kW stride 0) .scalar)))) := do
  match s.impl with
  | .eager sess =>
      EagerSession.smoothMaxPool2d (α := α) sess (kH := kH) (kW := kW) (inH := inH) (inW := inW)
        (inC := inC) (stride := stride) (h1 := h1) (h2 := h2) x beta
  | .compiled sess =>
      _root_.Runtime.Autograd.Torch.Internal.SessionIR.smoothMaxPool2d (α := α) sess
        (kH := kH) (kW := kW) (inH := inH) (inW := inW) (inC := inC) (stride := stride)
        (h1 := h1) (h2 := h2) x beta

/--
2D average pooling on a CHW tensor.

PyTorch analogy: `torch.nn.functional.avg_pool2d` (channel-first layout).
-/
def avgPool2d {α : Type} (s : Session α) [Context α] [DecidableEq Shape]
  {kH kW inH inW inC stride : Nat} (h1 : kH ≠ 0) (h2 : kW ≠ 0)
  (x : _root_.Runtime.Autograd.Torch.TensorRef α (.dim inC (.dim inH (.dim inW .scalar)))) :
  IO (_root_.Runtime.Autograd.Torch.TensorRef α
    (.dim inC (.dim (Spec.Shape.slidingWindowOutDim inH kH stride 0) (.dim (Spec.Shape.slidingWindowOutDim inW kW stride 0) .scalar)))) := do
  match s.impl with
  | .eager sess =>
      EagerSession.avgPool2d (α := α) sess (kH := kH) (kW := kW) (inH := inH) (inW := inW)
        (inC := inC) (stride := stride) h1 h2 x
  | .compiled sess =>
      _root_.Runtime.Autograd.Torch.Internal.SessionIR.avgPool2d (α := α) sess
        (kH := kH) (kW := kW) (inH := inH) (inW := inW) (inC := inC) (stride := stride)
        h1 h2 x

end Session

end TorchLean
end Autograd
end Runtime
