/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import NN.Floats.NeuralFloat.Format.Formats
public import NN.Floats.NeuralFloat.Format.Generic

/-!
# Standard Format Theorems

Connections between the generic format predicate and the concrete FIX, FLX, and FLT families.
The fixed-point equivalence is the first instance of the generic pattern used by the floating-point
families.
-/

@[expose] public section

namespace TorchLean.Floats

variable {β : NeuralRadix}

/-- The generic format generated by `FIXExp emin` is contained in `FIXFormat emin`. -/
theorem FIXFormat_of_generic (emin : ℤ) (x : ℝ)
    (hx : neuralGenericFormat β (FIXExp emin) x) : FIXFormat (β := β) emin x := by
  refine ⟨
    { mantissa := ⌊neuralScaledMantissa β (FIXExp emin) x⌋, exponent := emin }, ?_, rfl⟩
  simpa [neuralGenericFormat, neuralCexp, FIXExp] using hx

/-- Every fixed-point value belongs to the generic format generated by `FIXExp emin`. -/
theorem generic_of_FIXFormat (emin : ℤ) (x : ℝ) (hx : FIXFormat (β := β) emin x) :
    neuralGenericFormat β (FIXExp emin) x := by
  obtain ⟨f, hxf, hfe⟩ := hx
  apply neural_generic_format_of_scaled_mantissa_int
    (β := β) (fexp := FIXExp emin) x f.mantissa
  calc
    neuralScaledMantissa β (FIXExp emin) x = x * neuralBpow β (-emin) := by
      simp [neuralScaledMantissa, neuralCexp, FIXExp]
    _ = ((f.mantissa : ℝ) * neuralBpow β f.exponent) * neuralBpow β (-emin) := by
      rw [hxf, neuralToReal]
    _ = ((f.mantissa : ℝ) * neuralBpow β emin) * neuralBpow β (-emin) := by rw [hfe]
    _ = (f.mantissa : ℝ) * (neuralBpow β emin * neuralBpow β (-emin)) := by ring
    _ = (f.mantissa : ℝ) * neuralBpow β (emin + -emin) := by
      rw [neuralBpow.add_exp]
    _ = f.mantissa := by simp [neuralBpow]

/-- `FIXFormat` and the corresponding generic format describe the same real values. -/
theorem generic_format_FIX_iff (emin : ℤ) (x : ℝ) :
    neuralGenericFormat β (FIXExp emin) x ↔ FIXFormat (β := β) emin x :=
  ⟨FIXFormat_of_generic emin x, generic_of_FIXFormat emin x⟩

/-- A nonnegative radix power agrees with the corresponding natural-number power. -/
theorem neuralBpow_eq_natPow (p : ℤ) (hp : 0 ≤ p) :
    neuralBpow β p = (β.base ^ p.natAbs : ℕ) := by
  obtain ⟨n, rfl⟩ := Int.eq_ofNat_of_zero_le hp
  simp [neuralBpow, NeuralRadix.toReal]

/-- The generic `FLXExp` format satisfies the explicit FLX mantissa bound. -/
theorem FLXFormat_of_generic (prec : ℤ) (hprec : 0 < prec) (x : ℝ)
    (hx : @neuralGenericFormat β (FLXExp prec) (flxValidExp prec hprec) x) :
    FLXFormat (β := β) prec x := by
  letI : NeuralValidExp (FLXExp prec) := flxValidExp prec hprec
  let m : ℤ := ⌊neuralScaledMantissa β (FLXExp prec) x⌋
  let e : ℤ := neuralCexp β (FLXExp prec) x
  have hsint : neuralScaledMantissa β (FLXExp prec) x = m := by
    obtain ⟨n, hn⟩ :=
      (neural_generic_format_iff_scaled_mantissa_int
        (β := β) (fexp := FLXExp prec) x).mp hx
    dsimp [m]
    rw [hn]
    simp
  refine ⟨{ mantissa := m, exponent := e }, ?_, ?_⟩
  · unfold neuralGenericFormat at hx
    change x = (m : ℝ) * neuralBpow β e
    exact hx
  · by_cases hx0 : x = 0
    · subst x
      have hm0 : m = 0 := by simp [m, neuralScaledMantissa]
      rw [hm0]
      exact pow_pos (Nat.zero_lt_of_lt β.base_valid) _
    · have hbpos : 0 < neuralBpow β e := neuralBpow.pos β e
      have he : e = neuralMagnitude β x - prec := by simp [e, neuralCexp, FLXExp]
      have hsdiv : neuralScaledMantissa β (FLXExp prec) x =
          x / neuralBpow β e :=
        neuralScaledMantissa_eq_div (β := β) (fexp := FLXExp prec) x
      have hslt : abs (neuralScaledMantissa β (FLXExp prec) x) < neuralBpow β prec := by
        rw [hsdiv, abs_div, abs_of_pos hbpos, he]
        calc
          abs x / neuralBpow β (neuralMagnitude β x - prec) <
              neuralBpow β (neuralMagnitude β x) /
                neuralBpow β (neuralMagnitude β x - prec) :=
            (div_lt_div_iff_of_pos_right (neuralBpow.pos β _)).2
              (abs_lt_neuralBpow_magnitude β x hx0)
          _ = neuralBpow β prec := by
            rw [← neuralBpow.sub_exp]
            congr 1
            linarith
      have hmcast : (m.natAbs : ℝ) < neuralBpow β prec := by
        rw [hsint] at hslt
        have hmabs : (m.natAbs : ℝ) = abs (m : ℝ) := by
          cases m with
          | ofNat n => simp
          | negSucc n =>
              rw [Int.cast_negSucc, abs_of_neg]
              · norm_num
              · exact neg_neg_of_pos (by positivity : (0 : ℝ) < (n + 1 : ℕ))
        rwa [hmabs]
      have hpnonneg : 0 ≤ prec := hprec.le
      rw [neuralBpow_eq_natPow (β := β) prec hpnonneg] at hmcast
      exact_mod_cast hmcast

/-- Every explicit bounded-mantissa FLX value belongs to the corresponding generic format. -/
theorem generic_of_FLXFormat (prec : ℤ) (hprec : 0 < prec) (x : ℝ)
    (hx : FLXFormat (β := β) prec x) :
    @neuralGenericFormat β (FLXExp prec) (flxValidExp prec hprec) x := by
  letI : NeuralValidExp (FLXExp prec) := flxValidExp prec hprec
  obtain ⟨f, hxf, hmant⟩ := hx
  by_cases hm0 : f.mantissa = 0
  · have hx0 : x = 0 := by simp [hxf, neuralToReal, hm0]
    rw [hx0]
    exact neural_generic_format_zero
  · have hx0 : x ≠ 0 := by
      rw [hxf, neuralToReal]
      exact mul_ne_zero (by exact_mod_cast hm0) (neuralBpow.ne_zero β f.exponent)
    have hmabs : abs (f.mantissa : ℝ) = (f.mantissa.natAbs : ℝ) := by
      cases f.mantissa with
      | ofNat n => simp
      | negSucc n =>
          rw [Int.cast_negSucc, abs_of_neg]
          · norm_num
          · exact neg_neg_of_pos (by positivity : (0 : ℝ) < (n + 1 : ℕ))
    have hpnonneg : 0 ≤ prec := hprec.le
    have hmantR : abs (f.mantissa : ℝ) < neuralBpow β prec := by
      rw [hmabs, neuralBpow_eq_natPow (β := β) prec hpnonneg]
      exact_mod_cast hmant
    have habsx : abs x < neuralBpow β (f.exponent + prec) := by
      rw [hxf, neuralToReal, abs_mul, abs_of_pos (neuralBpow.pos β f.exponent)]
      calc
        abs (f.mantissa : ℝ) * neuralBpow β f.exponent <
            neuralBpow β prec * neuralBpow β f.exponent :=
          mul_lt_mul_of_pos_right hmantR (neuralBpow.pos β f.exponent)
        _ = neuralBpow β (f.exponent + prec) := by
          rw [← neuralBpow.add_exp]
          congr 1
          linarith
    have hmag : neuralMagnitude β x ≤ f.exponent + prec :=
      neuralMagnitude_le_of_abs_lt_bpow β x (f.exponent + prec) hx0 habsx
    have hcexp : neuralCexp β (FLXExp prec) x ≤ f.exponent := by
      simp [neuralCexp, FLXExp]
      linarith
    exact neural_generic_format_of_toReal_of_cexp_le f x hxf hcexp

/-- `FLXFormat` is exactly the generic format generated by `FLXExp`. -/
theorem generic_format_FLX_iff (prec : ℤ) (hprec : 0 < prec) (x : ℝ) :
    @neuralGenericFormat β (FLXExp prec) (flxValidExp prec hprec) x ↔
      FLXFormat (β := β) prec x :=
  ⟨FLXFormat_of_generic prec hprec x, generic_of_FLXFormat prec hprec x⟩

/-- The generic `FLTExp` format satisfies the explicit FLT mantissa and exponent bounds. -/
theorem FLTFormat_of_generic (emin prec : ℤ) (hprec : 0 < prec) (x : ℝ)
    (hx : @neuralGenericFormat β (FLTExp emin prec) (fltValidExp emin prec hprec) x) :
    FLTFormat (β := β) emin prec x := by
  letI : NeuralValidExp (FLTExp emin prec) := fltValidExp emin prec hprec
  let m : ℤ := ⌊neuralScaledMantissa β (FLTExp emin prec) x⌋
  let e : ℤ := neuralCexp β (FLTExp emin prec) x
  have hsint : neuralScaledMantissa β (FLTExp emin prec) x = m := by
    obtain ⟨n, hn⟩ :=
      (neural_generic_format_iff_scaled_mantissa_int
        (β := β) (fexp := FLTExp emin prec) x).mp hx
    dsimp [m]
    rw [hn]
    simp
  refine ⟨{ mantissa := m, exponent := e }, ?_, ?_, ?_⟩
  · unfold neuralGenericFormat at hx
    change x = (m : ℝ) * neuralBpow β e
    exact hx
  · by_cases hx0 : x = 0
    · subst x
      have hm0 : m = 0 := by simp [m, neuralScaledMantissa]
      rw [hm0]
      exact pow_pos (Nat.zero_lt_of_lt β.base_valid) _
    · have hbpos : 0 < neuralBpow β e := neuralBpow.pos β e
      have he : e = max (neuralMagnitude β x - prec) emin := by
        simp [e, neuralCexp, FLTExp]
      have hsdiv : neuralScaledMantissa β (FLTExp emin prec) x =
          x / neuralBpow β e :=
        neuralScaledMantissa_eq_div (β := β) (fexp := FLTExp emin prec) x
      have hdiff : neuralMagnitude β x - e ≤ prec := by
        rw [he]
        have := le_max_left (neuralMagnitude β x - prec) emin
        linarith
      have hslt : abs (neuralScaledMantissa β (FLTExp emin prec) x) <
          neuralBpow β prec := by
        rw [hsdiv, abs_div, abs_of_pos hbpos]
        calc
          abs x / neuralBpow β e <
              neuralBpow β (neuralMagnitude β x) / neuralBpow β e :=
            (div_lt_div_iff_of_pos_right hbpos).2
              (abs_lt_neuralBpow_magnitude β x hx0)
          _ = neuralBpow β (neuralMagnitude β x - e) :=
            (neuralBpow.sub_exp β _ _).symm
          _ ≤ neuralBpow β prec :=
            (neuralBpow_le_neuralBpow_iff β _ _).2 hdiff
      have hmcast : (m.natAbs : ℝ) < neuralBpow β prec := by
        rw [hsint] at hslt
        have hmabs : (m.natAbs : ℝ) = abs (m : ℝ) := by
          cases m with
          | ofNat n => simp
          | negSucc n =>
              rw [Int.cast_negSucc, abs_of_neg]
              · norm_num
              · exact neg_neg_of_pos (by positivity : (0 : ℝ) < (n + 1 : ℕ))
        rwa [hmabs]
      rw [neuralBpow_eq_natPow (β := β) prec hprec.le] at hmcast
      exact_mod_cast hmcast
  · simp [e, neuralCexp, FLTExp]

/-- Every explicit bounded-mantissa FLT value belongs to the corresponding generic format. -/
theorem generic_of_FLTFormat (emin prec : ℤ) (hprec : 0 < prec) (x : ℝ)
    (hx : FLTFormat (β := β) emin prec x) :
    @neuralGenericFormat β (FLTExp emin prec) (fltValidExp emin prec hprec) x := by
  letI : NeuralValidExp (FLTExp emin prec) := fltValidExp emin prec hprec
  obtain ⟨f, hxf, hmant, hexp⟩ := hx
  by_cases hm0 : f.mantissa = 0
  · have hx0 : x = 0 := by simp [hxf, neuralToReal, hm0]
    rw [hx0]
    exact neural_generic_format_zero
  · have hx0 : x ≠ 0 := by
      rw [hxf, neuralToReal]
      exact mul_ne_zero (by exact_mod_cast hm0) (neuralBpow.ne_zero β f.exponent)
    have hmabs : abs (f.mantissa : ℝ) = (f.mantissa.natAbs : ℝ) := by
      cases f.mantissa with
      | ofNat n => simp
      | negSucc n =>
          rw [Int.cast_negSucc, abs_of_neg]
          · norm_num
          · exact neg_neg_of_pos (by positivity : (0 : ℝ) < (n + 1 : ℕ))
    have hmantR : abs (f.mantissa : ℝ) < neuralBpow β prec := by
      rw [hmabs, neuralBpow_eq_natPow (β := β) prec hprec.le]
      exact_mod_cast hmant
    have habsx : abs x < neuralBpow β (f.exponent + prec) := by
      rw [hxf, neuralToReal, abs_mul, abs_of_pos (neuralBpow.pos β f.exponent)]
      calc
        abs (f.mantissa : ℝ) * neuralBpow β f.exponent <
            neuralBpow β prec * neuralBpow β f.exponent :=
          mul_lt_mul_of_pos_right hmantR (neuralBpow.pos β f.exponent)
        _ = neuralBpow β (f.exponent + prec) := by
          rw [← neuralBpow.add_exp]
          congr 1
          linarith
    have hmag : neuralMagnitude β x ≤ f.exponent + prec :=
      neuralMagnitude_le_of_abs_lt_bpow β x (f.exponent + prec) hx0 habsx
    have hcexp : neuralCexp β (FLTExp emin prec) x ≤ f.exponent := by
      simp [neuralCexp, FLTExp]
      constructor <;> linarith
    exact neural_generic_format_of_toReal_of_cexp_le f x hxf hcexp

/-- `FLTFormat` is exactly the generic format generated by `FLTExp`. -/
theorem generic_format_FLT_iff (emin prec : ℤ) (hprec : 0 < prec) (x : ℝ) :
    @neuralGenericFormat β (FLTExp emin prec) (fltValidExp emin prec hprec) x ↔
      FLTFormat (β := β) emin prec x :=
  ⟨FLTFormat_of_generic emin prec hprec x, generic_of_FLTFormat emin prec hprec x⟩

end TorchLean.Floats
